### PR TITLE
Route Views Issues v0.1.0

### PR DESCRIPTION
**Pull request by terminalstderr**
This pull request is to approve all aspects of the '0.1.0 (pre-release) of our public issue queue.'

> ℹ This pull request approval will apply to all aspects, but the actual changes included here are only to the navigation system. This is because there is a chicken-and-egg-situation: I want y'all to review the [rendered 'issue templates'](https://github.com/routeviews/public/issues/new/choose), but that means that the changes have to be in the "main" branch before I've even made this Pull Request (into the "main" branch). 😵

> ℹ This is still a 'pre-release.' I.e. Approving this PR does *not* imply approval to announce these drafts to the general public.

### Review Instructions

* Review all pages in the ["Route Views Issues" website (GitHub Page) produced from the "docs/" directory via MkDocs](https://routeviews.github.io/public/). Specifically, please pay close attention to:
   * ensure "Overview" looks good, and
   * ensure the "Voting Guide" makes good sense.

### Changes

This Pull Request only contains a change to the navigation of the site, i.e. the addition of a "Submit an Issue" button in the main navigation of the site (see the screenshot below).

### CODE REVIEW

**Comment by hanskuhn** [comment]
Looks like a good start. Are these pages only for community input tracking? I'd prefer a title that is more descriptive than "Route Views Issues", e.g. "Route Views feature tracker". Title is just an example as I'm not clear yet on the scope.

**Review by hanskuhn — APPROVED** [review]
Emoji!

**Review by kcclaffy — APPROVED** [review]
lgtm

**Comment by terminalstderr** [comment]
> Looks like a good start. Are these pages only for community input tracking? I'd prefer a title that is more descriptive than "Route Views Issues", e.g. "Route Views feature tracker". Title is just an example as I'm not clear yet on the scope.

@hanskuhn, good point, it has been hard to determine scope/boundaries from my perspective also. I like the idea of having strong boundaries between our 'services', but I'm unsure how to dedicate this repo. I'm thinking either we:

1. consider this repo to be a 'public issue queue service' only, or 
2. this repo could be the place for all public technical documentation.
 
My bias is towards considering this repo to be the 'public issue queue service' only. For tech docs, I am thinking we can make a private and public 'handbook.' (I've actually started the private [handbook repo](https://github.com/routeviews/handbook/tree/main/docs) as a place for tech docs that didn't seem to fit in the 'infra' repo.

Some ideas for name off the top of my head:
* Route Views GitHub Issues
* Route Views Feature Tracker
* Route Views Backlog
* Route Views Community Backlog
* Route Views' Priorities
* Route Views Issues

**Comment by terminalstderr** [comment]
Name chosen for this site: "Route Views Wish List"

**Pull request merged**
